### ISSUE TITLE
ATC Setup with cenrtal ATC system

### ISSUE THREAD

**Issue by ZEPWALLNERM** [abaplint/abaplint-sci-server#1274]
Hi, 

i wonder how to setup abaplint with an central ATC system where the development systems are only connected to the central ATC server.
Will it work to create empty packages on the central system so that the abalint config can work with them?

Honestly i doubt that it will work. 
What would be the correct approach here? 

FYI: We try to use github as a code review plattform which should use abaplint findings.

**Comment by larshp** [comment]
Hi,
I recommend using [abaplint.app](https://github.com/marketplace/abaplint), instead of central ATC, and instead of abaplint-sci-server

**Comment by ZEPWALLNERM** [comment]
Thanks for confirming me that. 
Will have a look on this.

**Comment by larshp** [comment]
feel free to contact me on hvam@heliconialabs.com for a demo/and/or talk about pros and cons

**Comment by larshp** [comment]
continuing by email, closing
