### ISSUE TITLE
abaplint Test Server not available

### ISSUE THREAD

**Issue by HuprichT** [abaplint/abaplint-sci-server#1575]
Following the Link http://[sci.abaplint.org](http://sci.abaplint.org/)/ results in Error "Host not available (DNS_PROBE_FINISHED_NXDOMAIN)"

Attempts were made via Browser and abaplint Client Config Dialog.

![image](https://github.com/abaplint/abaplint-sci-server/assets/45813255/6281bf8c-88d1-4624-aad2-5c88bd644976)
![image](https://github.com/abaplint/abaplint-sci-server/assets/45813255/beb643af-4e97-4d88-800a-aa0af02bec4b)

**Comment by larshp** [comment]
yea, its down, no plans to have it up again, sorry
