### ISSUE TITLE
message keys/check names

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-server#21]
https://github.com/abaplint/abaplint-cloud-foundry/issues/13#issuecomment-604509541

> we need to improve messages text. All those shortcuts look strange inside sci

@sbcgua

**Comment by sbcgua** [comment]
sample

![image](https://user-images.githubusercontent.com/15635498/77667738-46f7be80-6f8b-11ea-85fb-55338eeaab5d.png)

**Comment by larshp** [comment]
the data type in SAP is 10 characters, whereas the rule key in abaplint is string

can do a 10 character hash, but not sure it will be better

**Comment by sbcgua** [comment]
Hmm. But how other messages work ? (I have no idea about SCI internal :(( )

![image](https://user-images.githubusercontent.com/15635498/77672138-2d597580-6f91-11ea-980a-4bab8f8de046.png)

**Comment by larshp** [comment]
hmm, is the column in above screenshot the same as from the first screenshot? cannot tell as its not part of it

**Comment by sbcgua** [comment]
Yes, it is the lower part. But! I didn't run it via SCI actually.

![image](https://user-images.githubusercontent.com/15635498/77672865-149d8f80-6f92-11ea-9e78-4e44ac68c801.png)

You mean this one has just 10 symbols ?

![image](https://user-images.githubusercontent.com/15635498/77673085-60e8cf80-6f92-11ea-8240-d204e87a067f.png)

**Comment by larshp** [comment]
yes, message codes are only 10 characters, data element SCI_ERRC, and its used to group messages of the same type = rules in abaplint

**Comment by larshp** [comment]
see comment in https://github.com/abaplint/abaplint-abap-backend/issues/42

**Comment by larshp** [comment]
try again, latest version of the abap code

**Comment by sbcgua** [comment]
will do, but probably need to downport first ... I'll have a look in the coming days

**Comment by sbcgua** [comment]
hmmmm

![image](https://user-images.githubusercontent.com/15635498/87812502-f3c2b800-c868-11ea-9b52-64e2fe035f8f.png)

though debuggin showed that actually it is exception in check->run with `Max depth 0 reached for class ZCL_EDE_PARTNER. Exiting dependency walk`

**Comment by larshp** [comment]
double click the line to show the message

**Comment by mbtools** [comment]
This should work properly now
