### ISSUE TITLE
Add abaplint version to ping response

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint-sci-server#210]
/api/v1/ping => "abap is forevah!"

Cool... but I also want to know what's running on the server. :-)

https://github.com/abaplint/abaplint-sci-server/blob/master/src/api/index.ts

PS: Used by "Test Connection" in client

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint-sci-server/pull/200 adds the version to all responses as a header field

but yea, it could be nice to just have it part of the ping text

**Comment by sbcgua** [comment]
```json
{
  "success": 1,
  "payload": "Server is OK, abaplint version = 2.42.1"
}
```

**Comment by mbtools** [comment]
My server is running the latest as I can see in the response header:

`x-abaplint-version	2.43.0`

but I'm still getting the old response for /api/v1/ping

`{"success":1,"payload":"abap is forevah!"}`

how is that possible?

**Comment by mbtools** [comment]
after container restart:

`{"success":1,"payload":"Server is OK, abaplint version = 2.43.0"}`

👍
