### ISSUE TITLE
add REST endpoint to list rule names

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint-sci-server#218]
see https://github.com/abaplint/abaplint-sci-client/pull/158

**Comment by mbtools** [comment]
thx for the quick add. however, the response doesn't match a json array (as was intended, I think). This makes parsing harder than necessary:

`{"success":1,"payload":"[{\"key\":\"7bit_ascii\",\"title\":\"Check for 7bit ascii\"},{\"key\":\"abapdoc\",\"title\":\"Check abapdoc\"},{\"key\":\"allowed_object_naming\",\"title\":\"Allowed object naming\"},{\"key\":\"allowed_object_types\",\"title\":\"Check allowed object types\"},{\"key\":\"ambiguous_statement\",\"title\":\"Check for ambigious statements\"},{\"key\":\"avoid_use\",\"title\":\"Avoid use of certain statements\"},{\"key\":\"begin_end_names\",\"title\":\"Check BEGIN END names\"},{\"key\":\"begin_single_include\",\"title\":\"BEGIN contains single INCLUDE\"},{\"key\":...]"}`

I would expect

`{"success":1,"payload":[{"key":"7bit_ascii","title":"Check for 7bit ascii"},{"key":"abapdoc","title":"Check abapdoc"}, ...]}`

**Comment by larshp** [comment]
try again
