### ISSUE TITLE
docker build broken

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-sci-server#253]
`npm build` build into `./build/src` (not just `./build`). Was it the same before ? I have a feeling that it was `./build` directly. Also main and bin in package.json point to `build/server.js` - I'm sure I checked it was working

**Comment by larshp** [comment]
hmm, it was working 18 hours ago, https://github.com/abaplint/abaplint-sci-server/runs/1193139850

**Comment by sbcgua** [comment]
strange. I have tried in master too. Well, I'll have a look
