### ISSUE TITLE
Docker image fails with "Error: Cannot find module '/usr/src/app/build/server.js"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint-sci-server#256]
The current docker image produces messages like the below:

![image](https://user-images.githubusercontent.com/53995991/95008701-795e3480-061c-11eb-9da2-42fe9d4baec1.png)

Is this the same issue as #253?

**Comment by sbcgua** [comment]
yes, I'm working on it.

**Comment by ed-holland** [comment]
The current docker image still has the problem. Can you force publishing it?

**Comment by larshp** [comment]
it did publish a new version

**Comment by sbcgua** [comment]
are you sure you're using the latest image ? Just tried this:
![image](https://user-images.githubusercontent.com/15635498/95050017-8c900380-06f3-11eb-9dba-384d9b3b8707.png)

**Comment by ed-holland** [comment]
Just pulled the new version, but still the same issue.
![image](https://user-images.githubusercontent.com/53995991/95057927-168d9b80-06f7-11eb-8276-c586eca4366f.png)

![image](https://user-images.githubusercontent.com/53995991/95058088-52c0fc00-06f7-11eb-9f6c-da86dab630e4.png)

**Comment by sbcgua** [comment]
I'm very certain there is some issue with the pulling. I can see the digest in your screenshot differs from the last images at dockerhub.
![image](https://user-images.githubusercontent.com/15635498/95063825-899f0e00-0707-11eb-898d-71c9b8b1bf9e.png)

Do have an access to command line ? COuld you try pulling it with a specific tag ?

![image](https://user-images.githubusercontent.com/15635498/95064228-177af900-0708-11eb-913b-20a3bafa91a5.png)

**Comment by ed-holland** [comment]
yes, Portainer allows that. This issue has not changed. Still there.

![image](https://user-images.githubusercontent.com/53995991/95069859-958ad000-0707-11eb-8236-bef09feb809b.png)

The image is now showing with two tags (must have been this version already)
![image](https://user-images.githubusercontent.com/53995991/95069977-bce19d00-0707-11eb-99fc-b770b5d00dcc.png)

**Comment by sbcgua** [comment]
ok ... ehm ... but I cannot reproduce the issue really. Do you have an access to command line ? Could you `docker ps -a` and `docker image ls` there (pls mind other private containers if you have ones :)

**Comment by sbcgua** [comment]
hmm, looks OK ...
so ... what happens if you run:
```
docker ps -a | awk '{ print $1,$2 }' | grep abaplint | awk '{print $1 }' | xargs -I {} docker rm {}
docker run --rm -p 3000:3000 abaplint/abaplint-backend
```
The first command removes all abaplint containers (just in case)

**Comment by ed-holland** [comment]
Interestingly enough, just deleting and recreating the container using my compose file resolved the issue.
Very strange. Thanks a lot for helping me getting through this.

Details are now also showing up (using verbose)
![image](https://user-images.githubusercontent.com/53995991/95191419-09dd7600-07d1-11eb-9931-dc40960a900d.png)
