### ISSUE TITLE
move docker back to docker dir

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint-sci-server#96]
revert #41 (and ensure it works :) ) and also adjust build.yml filters (as the repo name changed)

P.S. after current PRs are merged
P.P.S just in case "why": files at root levels makes it a bit cluttered, and may become more cluttered if more compose scenarios are introduced. E.g. abaplint+nginx+ssl certs

**Comment by sbcgua** [comment]
notes:  `jq '.dependencies."@abaplint/core".version' -r package-lock.json` to extract version from package lock without installing all the deps

**Comment by larshp** [comment]
agree: should try to have less files at root level

**Comment by sbcgua** [comment]
improve todo:
- fix run/scripts
- add build&run script
- add cleanup script
- maybe link them to npm scripts (not sure, mixing things) ???

**Comment by sbcgua** [comment]
@larshp Are you using docker password or docker token as a secret ? Well, tokens are available now (I think it was not so before) - https://docs.docker.com/docker-hub/access-tokens/

**Comment by larshp** [comment]
tokens, 

![image](https://user-images.githubusercontent.com/5888506/95012601-432fad80-063a-11eb-9f28-f7e238b5ab83.png)
